### ISSUE TITLE
Inline pickers set a value when closing popup without selecting anything when current value is null

### ISSUE THREAD

**Issue by marc-mrt** [mui-org/material-ui-pickers#1030]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  2.2.4       |
| material-ui          |   3.9.3      |
| React                |   16.5.2      |
| Browser              |  firefox:latest       |
| Moment         |   2.24      |  |

## Steps to reproduce

1.  Have a inline date picker
2. Set initial value as null
3. Open picker and close it without selecting a date
4. It will select the today's date

## Expected behavior

Value should remain null

## Actual behavior

Today's date is selected

## Live example
https://codesandbox.io/s/ql0p18xpq9

**Comment by dmtrKovalenko** [comment]
Fixed in v3

**Comment by marc-mrt** [comment]
Issue is still not fixed, here is an updated code sandbox with all of the latest dependencies: https://codesandbox.io/s/wonderful-wood-fnznc

**Comment by SpearThruster** [comment]
I think you need to have onAccept prop for the onChange to not get triggered immediately ->  but still haven't tried the latest version.

**Comment by marc-mrt** [comment]
Just tried that, the onChange appears to be triggered before the onAccept anyways, so nothing I can really do here

**Comment by SpearThruster** [comment]
https://material-ui-pickers.dev/demo/datepicker

But it works here properly? What version are you using?

**Comment by marc-mrt** [comment]
Check out the code sandbox here: https://codesandbox.io/s/wonderful-wood-fnznc
Everything is in its latest version I believe
