### ISSUE TITLE
No possibility to recover from validation errors

### ISSUE THREAD

**Issue by nico1510** [mui-org/material-ui-pickers#1287]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.3   |
| material-ui          |     4.0.0    |
| React                |     16.8.6    |
| Browser              |  Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)      |
| Peer library         |        date-fns@2.0.0-beta.5  |

## Steps to reproduce

1. Go to the formik integration demo: https://material-ui-pickers.dev/guides/form-integration#formik-integration
2. In the textfield delete the last character (i.e. the 9 from 2019)
3. The textfield will now show an error
4. add the 9 back or type any valid date into the textfield

## Expected behavior

since the date is valid again now, I expect no validation errors.

## Actual behavior

the textfield will still show the error no matter what you do now 

## Live example

can be reproduced on the demo page: https://material-ui-pickers.dev/guides/form-integration#formik-integration

## proposal
Either onError should be called with `null` or `undefined` as argument instead of the error message or there should be another prop (e.g. `onSuccess`) which is called when validation was successful. Otherwise there's no easy way to know when to reset the error in the form (formik in this case).

**Comment by dmtrKovalenko** [comment]
Fixed already

**Comment by jmaister** [comment]
I am using the latest 3.x version and still having this problem.

      "@material-ui/pickers": "3.2.10",

Which version should I use to get it fixed ?
