### ISSUE TITLE
React does not recognize the `nodeRef` prop on a DOM element

### ISSUE THREAD

**Issue by giovanniantonaccio** [mui-org/material-ui-pickers#1790]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.10   |
| material-ui          |  4.9.14   |
| TypeScript           | 3.7.5        |
| React                |   ^16.12.0      |
| Browser              |  ^16.12.0   |
| date-fns      |     2.13.0    | 
| @date-io/date-fns | 1.3.13 |

## Steps to reproduce

1. Click to open the Modal
2. Look at the console

## Expected behavior

Modal open with no warning on the console

## Actual behavior

Component works correctly but the following warning is shown on the console: 

```Warning: React does not recognize the `nodeRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `noderef` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```

## Live example
https://codesandbox.io/s/eslint-codesandbox-qu2mi?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/8068067/82211747-5b976980-98df-11ea-8777-86f2770a3c6f.png)

**Comment by oliviertassinari** [comment]
@giovanniantonaccio We do no longer support v3. Do you have a reproduction with v4?

**Comment by oliviertassinari** [comment]
It seems to be fixed https://codesandbox.io/s/stoic-boyd-i2xe8?file=/src/App.js.

**Comment by giovanniantonaccio** [comment]
@oliviertassinari thanks for your answer! Do you already recommend upgrading to v4? 
If not, any ideas on when it will be available?

**Comment by oliviertassinari** [comment]
@giovanniantonaccio I think that you can already upgrade to v4. There are a couple more of breaking changes coming down the road, but we have definitely made progress since v3.

**Comment by jkirankumar1993** [comment]
@oliviertassinari I am already using version v4 and I am experiencing the same error.

**Comment by oliviertassinari** [comment]
Do you have a reproduction?

**Comment by jkirankumar1993** [comment]
@oliviertassinari yes. Getting that error for Dialog boxes

**Comment by NawarA** [comment]
I'm actually seeing this error too, but when I follow the stack trace, the only module thats using it is Slide.js 

![image](https://user-images.githubusercontent.com/2067616/82852867-f0d6c700-9eb8-11ea-8552-07ffa5e08e7d.png)

It does seem to be related to transition, as shown in the screenshot of slide.js's code

**Comment by oliviertassinari** [comment]
Please provide a full reproduction test case with the latest version (v4.0.0-alpha.7). This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/github/mui-org/material-ui/tree/master/examples/create-react-app-with-typescript) _may_ be a good starting point. Thank you!

**Comment by medvedca** [comment]
This is my first time ever, so I hope it works :) Live example of the issue. 

https://codesandbox.io/live/YE24pp

Also, forgive me for a little bit unnecessary (me thinks) amount of detail in the example, but it does show the issue in the context of a relatively elaborate workflow.

**Comment by jpodpro** [comment]
i'm getting this error with MUI core 4.11.0 and it appears to be related to the Transition component. downgrading to our previous 4.8.3 fixes the issue.

![image](https://user-images.githubusercontent.com/15255854/87993644-de839e80-ca9f-11ea-891a-9c6292ba2fb1.png)

**Comment by arttuka** [comment]
This issue is caused by an outdated version of react-transition-group. Updating to [v4.4.0](https://github.com/reactjs/react-transition-group/blob/master/CHANGELOG.md#440-2020-05-05) in your project should fix it.

**Comment by MutableLoss** [comment]
Thanks @arttuka This fix, worked for me. 

I was getting this exact error after updating to MUI ^4.9.0 (from ^4.3.0), and still using react-transistion-group 4.1.1.

_**Updating react-transistion-group to** **^4.4.0** removed the error from the secondary ThemeProvider component, completely._

**Comment by simplypixi** [comment]
MUI: **4.11.0**
react-transistion-group: **4.4.1**

And the issue still exists. :(

**Comment by ghost** [comment]
Explicitly install `react-transistion-group@4.4.1` fixed my issue.

**Comment by NawarA** [comment]
Is this solved in v5?
