### ISSUE TITLE
ToolbarComponent is not working for DesktopDateRangePicker or MobileDateRangePicker

### ISSUE THREAD

**Issue by aamirafridi** [mui-org/material-ui-pickers#1948]
I am trying to add some buttons in the toolbar but doesn't seem to be working

https://codesandbox.io/s/material-ui-date-range-qd0wz?file=/src/index.tsx

**Comment by aamirafridi** [comment]
toolbarTitle is also not working

**Comment by dmtrKovalenko** [comment]
> toolbarTitle is also not working

Must be fixed by #1914

**Comment by aamirafridi** [comment]
@dmtrKovalenko Which version should have the above fix?

**Comment by dmtrKovalenko** [comment]
The next

**Comment by oliviertassinari** [comment]
> toolbarTitle is also not working

@aamirafridi if you could test again once *@material-ui/pickers@v4.0.0-alpha.9* is released, it will be perfect :).

**Comment by oliviertassinari** [comment]
Also, I see that #1914 is missing a test case. If we could resolve the issue with one, it will be perfect.

**Comment by aamirafridi** [comment]
Sure, Can someone ping me once it is released? I will give it ago

**Comment by oliviertassinari** [comment]
@aamirafridi You can subscribe to new releases with:

<img width="343" alt="Capture d’écran 2020-07-03 à 15 33 33" src="https://user-images.githubusercontent.com/3165635/86474183-9562e900-bd42-11ea-9e05-51f903b5cbc5.png">

**Comment by aamirafridi** [comment]
Done, I will try after the next release

**Comment by aamirafridi** [comment]
oh no....
`shouldDisableDate` is not working :(

`shouldDisableDate={() => false}`

I can still select any date. https://codesandbox.io/s/material-ui-date-range-qd0wz?file=/src/index.tsx

**Comment by dmtrKovalenko** [comment]
I am seeing, that it is pretty common mistake. `shouldDisableDate` must return `true` in order to disable date. 

Isn’t it clear @aamirafridi?

**Comment by aamirafridi** [comment]
![image](https://media.giphy.com/media/jUwpNzg9IcyrK/source.gif)

it worked, sorry for the wrong alert

**Comment by aamirafridi** [comment]
renderDay also doesn't seems to be working https://codesandbox.io/s/material-ui-date-range-h3nlq?file=/src/index.tsx

**Comment by aamirafridi** [comment]
Same for autoOk
docs says default is [false](https://next.material-ui-pickers.dev/api/DateRangePicker) but calendar disappears after you select 2nd date
basically all props need to be checked

**Comment by aamirafridi** [comment]
shouldDisableYear is not working :(

**Comment by dmtrKovalenko** [comment]
This is already fixed in alpha.9

**Comment by aamirafridi** [comment]
ToolbarComponent is still not working https://codesandbox.io/s/material-ui-date-range-qd0wz?file=/src/index.tsx

**Comment by aamirafridi** [comment]
also, is autoOk is removed?

**Comment by aamirafridi** [comment]
I want the user to select a date, then I will highlight X-days onward from that date to show the user a range (user cannot select end date). I tried using default DatePicker but it doesn't allow showing multiple calendars :(
So I am using DateRange where with renderInput, I just render one Input and once From date is selected, I calculate To date and set it programmatically. I want to show the OK button to the user so the user can see the range and then click OK. I was ok with autoOk true which it will close itself on selecting the first date. 

**Update:**
just found disableCloseOnSelect

I wish there was a way to display cancel and Ok button even for the desktop to have complete control

**Comment by aamirafridi** [comment]
`disableCloseOnSelect` is not acting to previous `autOk`

e.g.
```javascript
onChange={(selectedDate) => {
          if (selectedDate[0]) {
            const endDate = addDays(selectedDate[0] as Date, Number(3));
            return props.onChange([selectedDate[0], endDate]);
          }
          props.onChange(selectedDate);
}}
```

setting end date programmatically use to close the date picker with autoOk. With `disableCloseOnSelect={false}` you have to click another date to make it close.

Also `disableCloseOnSelect` is confusing. Why not just `closeOnSelect/shouldCloseOnSelect`

**Comment by oliviertassinari** [comment]
> Also disableCloseOnSelect is confusing. Why not just closeOnSelect/shouldCloseOnSelect

Yeah, the problem is that the default value doesn't match the name convention we have for the components I have open #2050 so we don't forget to set `disableCloseOnSelect={true}` in v5.
