### ISSUE TITLE
DatePicker shows old value if new value is passed in while text input is focused

### ISSUE THREAD

**Issue by SpacePrincessAda** [mui-org/material-ui-pickers#2112]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

If the value for the DatePicker is changed while the text input is focused, the text input will not show the updated value. A situation where this is likely to occur is when a form is submitted with the enter key while the DatePicker input is still focused, and after the submit has been completed the form state is cleared.

The DatePicker correctly shows the updated value if the text input is not focused when the value is updated.

## Expected Behavior 🤔

I would expect the DatePicker text input to reflect the correct value at all times. If a new value is passed in, the DatePicker text input should show that value even if the input is focused.

## Steps to Reproduce 🕹

Sandbox: https://codesandbox.io/s/vigilant-lederberg-cqvnk?file=/src/App.jsx

Steps:

1. Click inside the text input to focus it.
2. While the input is focused, press enter to submit and reset the form.
3. Observe that `Value:` now shows that the form value is `null`, but the text input still shows the previous value.

To see that this works correctly when the text input is not focused:

1. Reload the page
2. Click the Submit button without clicking on the date input.
3. Observe that the text input is now empty and `Value: ` shows that the form value is `null`.

## Context 🔦

We have some forms that are cleared after data is submitted to allow the user to enter and submit a new set of data. This bug is a problem because the underlying value falls out of sync with what is displayed and the user may have no idea that this has happened, causing them to submit incorrect data.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | 4.11.0  |
| @material-ui/pickers | 4.0.0-alpha.12  |
| React       | 16.13.1 |

**Comment by eglavin** [comment]
I wonder would your problem be fixed by placing a blur event on the TextField which will only fire when an enter button is pressed?
```
onKeyDown={(e) => {
  if (e.which === 13) {
    e.target.blur();
    onSubmit(e);
  }
}}
```
So for your expected behaviour what do you mean when you say "text input to reflect the correct value at all times" if the value is to be set null on submit? Would the above cover in this situation or would perfer the users input to stay in focus on the input?

**Comment by SpacePrincessAda** [comment]
I have a temporary workaround that's similar to that, but yes, I would like to keep the input focused and I also still think that this behavior is unexpected. 

When I said I would expect the "text input to reflect the correct value at all times", what I meant was that if a new value is passed in to the DatePicker that value would be displayed, regardless of whether the input was focused. This is the way that all of the base Material-UI inputs behave. Having situations where a new value is passed into the component and it ignores that value seems like something that's likely to cause trouble.

**Comment by kstrombom-dutchie** [comment]
This is still an issue.

```
  const onStartDateInputChange = (value: Date | null) => {
    if (!isValid(value)) {
      setStartDate(new Date());
      return;
    }

    setStartDate(value);
  };
              <DateField
                value={startDate}
                onChange={(newValue) => onStartDateInputChange(newValue)}
              />
```

Entering an invalid date '02/30/2024' will update the DateField Value but the underlying TextField Value is still the invalid date.
